name: Deploy
on: 
  push:
    branches:
      - master
jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17.0.1'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Generate ~/.clasprc.json
        run: |
          LOGIN=$(cat <<-END
              {
                  "token": {
                      "access_token": "$ACCESS_TOKEN",
                      "refresh_token": "$REFRESH_TOKEN",
                      "scope": "https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly",
                      "token_type": "Bearer",
                      "id_token": "$ID_TOKEN",
                      "expiry_date": 1626836135899
                  },
                  "oauth2ClientSettings": {
                      "clientId": "$CLIENT_ID",
                      "clientSecret": "$CLIENT_SECRET",
                      "redirectUri": "http://localhost"
                  },
                  "isLocalCreds": false
              }
          END
          )
          echo $LOGIN > ~/.clasprc.json

      - name: Npm install & deploy
        run: |
          cd merchant_recon
          npm install
          npm run deploy

